### ISSUE TITLE
Plugin throws an error in case the Fela component is being exported immediately

### ISSUE THREAD

**Issue by HamidAghdaee** [louisscruz/babel-plugin-transform-react-fela-display-name#2]
For example, in the following case:

```
export const ZoneNameWrapper = createComponent(({ transitionLoading }) => ({
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  whiteSpace: 'nowrap',
  opacity: transitionLoading ? 0.5 : undefined
}));
```

We see the following error:

```
    /Users/hamidaghdaee/dev/stratus/src/dash/core/component-zone-selector/src/Card.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?

      11 |     const right = t.stringLiteral(componentName);
      12 |     const displayNameAssignment = t.toStatement(t.assignmentExpression('=', left, right));
    > 13 |     initialLineNodePath.insertAfter(displayNameAssignment);
         |                         ^
      14 |   };
      15 | 
      16 |   const identifierComesFromReactFela = (

      at NodePath.insertAfter (node_modules/babel-traverse/lib/path/modification.js:175:13)
      at handleInjectDisplayName (../babel-plugin-transform-react-fela-display-name/src/index.js:13:25)
      at injectDisplayName (../babel-plugin-transform-react-fela-display-name/src/index.js:136:13)
      at PluginPass.VariableDeclarator (../babel-plugin-transform-react-fela-display-name/src/index.js:154:13)
      at newFn (node_modules/babel-traverse/lib/visitors.js:276:21)
      at NodePath._call (node_modules/babel-traverse/lib/path/context.js:76:18)
      at NodePath.call (node_modules/babel-traverse/lib/path/context.js:48:17)
      at NodePath.visit (node_modules/babel-traverse/lib/path/context.js:105:12)
      at TraversalContext.visitQueue (node_modules/babel-traverse/lib/context.js:150:16)
      at TraversalContext.visitMultiple (node_modules/babel-traverse/lib/context.js:103:17)
```

**Comment by louisscruz** [comment]
Again, thank you for the help!
